// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVikunSiPgKggQfr7Jhmcn3R-Gqp_6nA8',
    appId: '1:563927650029:web:8499a6301154ccd82486e4',
    messagingSenderId: '563927650029',
    projectId: 'pluscart',
    authDomain: 'pluscart.firebaseapp.com',
    databaseURL: 'https://pluscart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pluscart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLV6lv96ec5PDBjO_HZAgcgHC3xWjyZeg',
    appId: '1:563927650029:android:a0398177dd6e98ae2486e4',
    messagingSenderId: '563927650029',
    projectId: 'pluscart',
    databaseURL: 'https://pluscart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pluscart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPm9SFfwnRHsnFpOY3FzjCU1744MSbV8',
    appId: '1:563927650029:ios:d44002900897c1182486e4',
    messagingSenderId: '563927650029',
    projectId: 'pluscart',
    databaseURL: 'https://pluscart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pluscart.firebasestorage.app',
    iosBundleId: 'com.mrjoo.pluscart',
  );
}
